# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
safe: true


# edit here to achieve your personal greatness
#url: http://username.github.io/
title: Ashish Kumar Shah
author: Ashish Kumar Shah
description: Personal blog and resume
avatar: photo.JPG
email: ashish@phodu.com
github: ashishkumarshah
twitter: ashishisawesome
linkedin: ashishkumarshah
facebook: ashish.kumar.shah
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-47497737-1


# needed for travis-ci build
exclude: [vendor]
